version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_proyecto
    ports:
      - "27017:27017"
    networks:
      - red_proyecto


  script_service:
    image: javitss/apibicis:latest
    container_name: apibicis
    depends_on:
      - mongodb
    networks:
      - red_proyecto

networks:
  red_proyecto:
    driver: bridge